/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    GithubRepo: typeof import('./components/GithubRepo.vue')['default']
    PenCursor: typeof import('./components/PenCursor.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResizePan: typeof import('./components/ResizePan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgCanvas: typeof import('./components/SvgCanvas.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
