/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    GithubRepo: typeof import('./components/GithubRepo.vue')['default']
    PenCursor: typeof import('./components/PenCursor.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    ResizePan: typeof import('./components/ResizePan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgCanvas: typeof import('./components/SvgCanvas.vue')['default']
    SvgPreviewer: typeof import('./components/SvgPreviewer.vue')['default']
  }
}
